# 在你的 _config.yml 文件中设置
theme: paper
# Site
title: Bullshit Practice
subtitle: 感谢电，网络，计算机。
description: 
keywords: 
author: Zsc
language: zh-CN
timezone:
# 同时为了代码高亮，你需要将下面的内容粘贴到该文件（如果之前存在highlight字段，记得删除后再粘贴）
highlight:
  hljs: true
  enable: true
  line_number: false
  auto_detect: true
  tab_replace: ''

# Uncomment to disable sidebar
# toc: false
link: false
# archives: false
# categories: false
# tags: false