name: Sync Discussions to Hugo

on:
  discussion:
    types: [created]  # 监听 discussion 创建
  workflow_dispatch:  # 允许手动触发

env:
  ACTIONS_STEP_DEBUG: true
  ACTIONS_RUNNER_DEBUG: true

jobs:
  sync-discussions:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 需要写入权限
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive

      - name: Fetch and Process Discussion
        run: |
          echo '${{ toJson(github.event.discussion) }}' > new_discussion.json

          title=$(jq -r '.title // empty' new_discussion.json)
          titleJson=$(jq -c '.title' new_discussion.json)
          createdAt=$(jq -r '.created_at // empty' new_discussion.json)
          body=$(jq -r '.body // empty' new_discussion.json)
          labelsJson=$(jq -c '[.labels[].name]' new_discussion.json)

          if [[ -z "$title" || -z "$body" ]]; then
            echo "No valid discussion data found. Exiting."
            exit 0
          fi

          markdown_content="---
          title: $titleJson
          date: $createdAt
          tags: $labelsJson
          ---
          
          $body"

          mkdir -p content/articles
          filename="content/articles/$title.md"
          echo "$markdown_content" > "$filename"

      - name: Commit and Push New Post
        run: |
          # git config --global user.name "github-actions[bot]"
          # git config --global user.email "github-actions[bot]@users.noreply.github.com"
          # git add content/articles/*.md
          # git commit -m "New Discussion Post: $title" || echo "No changes to commit"
          # git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/MarkRushB/markrushb.github.io.git main || echo "No changes to push"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add content/articles/*.md
          git commit -m "New Discussion Post: $title [skip ci]" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/MarkRushB/markrushb.github.io.git main || echo "No changes to push"
      - name: Trigger Build & Deploy Workflow
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GH_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/MarkRushB/markrushb.github.io/actions/workflows/build-and-deploy.yml/dispatches \
            -d '{"ref":"main"}'
